name: Daily Expiry Alerts

on:
  schedule:
    - cron: "0 8 * * *"   # runs every day at 08:00 UTC
  workflow_dispatch:      # allow manual run too

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install firebase-admin

      - name: Run script
        run: node sendAlerts.js
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
